name = "yoga-crm-demo"
account_id = "cf7950ba25ac14c265564cccdf9104a5"
compatibility_date = "2024-09-23"
pages_build_output_dir = "./dist"

[assets]
directory = "./dist"
not_found_handling = "single-page-application"

